const products=[
 {id:1,sku:"MV-SHOE-001",name:"The Regent Runner",category:"shoes",type:"Sneakers",price:185000,old:220000,image:"https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=700&q=80",tag:"Bestseller",desc:"A sculpted everyday runner with effortless presence."},
 {id:2,sku:"MV-SHOE-002",name:"The Verona Loafer",category:"shoes",type:"Loafers",price:245000,image:"https://images.unsplash.com/photo-1614252369475-531eba835eb1?auto=format&fit=crop&w=700&q=80",tag:"New",desc:"Polished leather, considered down to the last stitch."},
 {id:3,sku:"MV-SHOE-003",name:"The Muse Heel",category:"shoes",type:"Women's shoes",price:210000,old:250000,image:"https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=700&q=80",tag:"-16%",desc:"A confident silhouette for after-dark occasions."},
 {id:4,sku:"MV-WATCH-001",name:"The Meridian",category:"watches",type:"Luxury watch",price:390000,image:"https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=700&q=80",tag:"New",desc:"A quiet statement in brushed steel and midnight black."},
 {id:5,sku:"MV-WATCH-002",name:"The Axis Chrono",category:"watches",type:"Lifestyle watch",price:325000,image:"https://images.unsplash.com/photo-1524805444758-089113d48a6d?auto=format&fit=crop&w=700&q=80",tag:"Bestseller",desc:"Precision and character for the modern daily ritual."},
 {id:6,sku:"MV-SHOE-004",name:"The Court Classic",category:"shoes",type:"Sneakers",price:165000,image:"https://images.unsplash.com/photo-1552346154-21d32810aba3?auto=format&fit=crop&w=700&q=80",tag:"New",desc:"A considered low-top with a clean, timeless line."},
 {id:7,sku:"MV-WATCH-003",name:"The Atelier",category:"watches",type:"Luxury watch",price:510000,image:"https://images.unsplash.com/photo-1539874754764-5a96559165b0?auto=format&fit=crop&w=700&q=80",tag:"Limited",desc:"Architectural proportions and an exceptional finish."},
 {id:8,sku:"MV-SHOE-005",name:"The Porter Slide",category:"shoes",type:"Sandals",price:120000,old:145000,image:"https://images.unsplash.com/photo-1603487742131-4160ec999306?auto=format&fit=crop&w=700&q=80",tag:"-17%",desc:"The easy, elevated essential for off-duty days."}
];
const rates={NGN:1,GHS:.0076,BTC:.0000000048}, symbols={NGN:"₦",GHS:"GH₵",BTC:"₿"};
let currency=localStorage.getItem("mv-currency")||"NGN", cart=JSON.parse(localStorage.getItem("mv-cart")||"[]"), wishlist=JSON.parse(localStorage.getItem("mv-wishlist")||"[]"), activeFilter="all";
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
function money(value){let converted=value*rates[currency];return currency==="BTC"?`${symbols[currency]}${converted.toFixed(6)}`:`${symbols[currency]}${Math.round(converted).toLocaleString()}`}
function save(){localStorage.setItem("mv-cart",JSON.stringify(cart));localStorage.setItem("mv-wishlist",JSON.stringify(wishlist));localStorage.setItem("mv-currency",currency)}
function renderProducts(){let list=products.filter(p=>activeFilter==="all"||p.category===activeFilter);const sort=$("#sort-products").value;if(sort==="price-low")list.sort((a,b)=>a.price-b.price);if(sort==="price-high")list.sort((a,b)=>b.price-a.price);$("#product-grid").innerHTML=list.map(p=>`<article class="product-card"><div class="product-image"><span class="badge">${p.tag}</span><button class="heart ${wishlist.includes(p.id)?"active":""}" data-wish="${p.id}" aria-label="Wishlist ${p.name}">${wishlist.includes(p.id)?"♥":"♡"}</button><img src="${p.image}" alt="${p.name}" loading="lazy"><button class="quick-add" data-add="${p.id}">Quick add +</button></div><div class="product-meta" data-view="${p.id}"><small>${p.type}</small><h3>${p.name}</h3><p>${money(p.price)}${p.old?`<span class="old-price">${money(p.old)}</span>`:""}</p><div class="rating">★★★★★ <span>(24)</span></div></div></article>`).join("")}
function renderCart(){let count=cart.reduce((sum,item)=>sum+item.qty,0);$("#cart-count").textContent=count;$("#wishlist-count").textContent=wishlist.length;$("#cart-items").innerHTML=cart.length?cart.map(item=>{let p=products.find(x=>x.id===item.id);return `<div class="cart-item"><img src="${p.image}" alt=""><div><h4>${p.name}</h4><span>${money(p.price)}</span><div class="qty"><button data-qty="${p.id}" data-delta="-1">−</button>${item.qty}<button data-qty="${p.id}" data-delta="1">+</button><button data-remove="${p.id}">Remove</button></div></div></div>`}).join(""):`<p style="color:var(--muted);padding:25px 0">Your cart is waiting for something exceptional.</p>`;$("#cart-total").textContent=money(cart.reduce((sum,item)=>sum+products.find(p=>p.id===item.id).price*item.qty,0))}
function add(id){let item=cart.find(x=>x.id===id);item?item.qty++:cart.push({id,qty:1});save();renderCart()}
function showQuick(id){let p=products.find(x=>x.id===id);$("#quick-content").innerHTML=`<div class="quick-content"><img src="${p.image}" alt="${p.name}"><div><p class="eyebrow">${p.type}</p><h2>${p.name}</h2><p>${money(p.price)}</p><p style="color:var(--muted);line-height:1.8">${p.desc}</p><button class="button button-dark" data-add="${p.id}">Add to cart <span>↗</span></button></div></div>`;$("#quick-view").classList.add("open");$("#modal-backdrop").classList.add("open")}
let accountUser=JSON.parse(localStorage.getItem("mv-user")||"null"), recent=JSON.parse(localStorage.getItem("mv-recent")||"[]");
const API_BASE="http://localhost:4000";
async function api(path,options={}){let response=await fetch(`${API_BASE}${path}`,{...options,credentials:"include",headers:{"Content-Type":"application/json",...(options.headers||{})}});let body=response.status===204?null:await response.json();if(!response.ok)throw new Error(body?.error||"Request failed");return body}
let siteAuthenticated=false;
function setGateMode(signup=false){$("#gate-panel").classList.toggle("signup-mode",signup);$("#gate-title").textContent=signup?"Create your account":"Sign in to continue";$("#gate-eyebrow").textContent=signup?"JOIN THE INNER CIRCLE":"YOUR ACCOUNT";$("#gate-subtitle").textContent=signup?"Create an account to access the MAYOR VOGUE collection.":"Access the MAYOR VOGUE collection.";$("#gate-name").required=signup;$("#gate-confirm").required=signup;$(".gate-submit").innerHTML=signup?'Create account <span>↗</span>':'Sign in <span>↗</span>';$("#gate-switch").innerHTML=signup?'Already a member? <button type="button">Sign in</button>':'New to MAYOR VOGUE? <button type="button">Create an account</button>';$("#gate-switch button").onclick=()=>setGateMode(!signup)}
function unlockSite(user){siteAuthenticated=true;accountUser=user;document.body.classList.remove("auth-locked");$("#site-gate").classList.remove("open");$("#header-logout").style.display="inline-block";$("#admin-nav-link").hidden=user.role!=="ADMIN";$("#gate-auth-form").reset()}
function lockSite(){siteAuthenticated=false;accountUser=null;document.body.classList.add("auth-locked");$("#site-gate").classList.add("open");$("#header-logout").style.display="none";$("#admin-nav-link").hidden=true;setGateMode(false)}
async function initializeSiteAuth(){try{let result=await api("/api/auth/me");unlockSite(result.user)}catch{lockSite()}}
$("#header-logout").onclick=async()=>{try{await api("/api/auth/logout",{method:"POST"})}catch(error){console.error(error)}finally{lockSite()}};
$("#gate-auth-form").onsubmit=async event=>{event.preventDefault();let signup=$("#gate-panel").classList.contains("signup-mode"),email=$("#gate-email").value.trim().toLowerCase(),password=$("#gate-password").value;if(signup&&password!==$("#gate-confirm").value){$("#gate-message").textContent="Passwords do not match.";$("#gate-message").style.color="#b45c48";return}try{let result=await api(signup?"/api/auth/register":"/api/auth/login",{method:"POST",body:JSON.stringify(signup?{name:$("#gate-name").value.trim(),email,password}:{email,password})});$("#gate-message").textContent=result.message||"Signed in successfully.";unlockSite(result.user)}catch(error){$("#gate-message").textContent=error.message;$("#gate-message").style.color="#b45c48"}};
$("#gate-forgot").onclick=async()=>{let email=prompt("Enter the email address for your password reset link:");if(email){try{let result=await api("/api/auth/forgot-password",{method:"POST",body:JSON.stringify({email})});$("#gate-message").textContent=result.message}catch(error){$("#gate-message").textContent=error.message}}};
function pageAuthMode(signup){$("#auth-page-form").classList.toggle("signup-mode",signup);$("#auth-page-title").textContent=signup?"Create your account":"Sign in";$("#auth-page-subtitle").textContent=signup?"Join MAYOR VOGUE for a more personal experience.":"Enter your details to continue.";$("#page-name").required=signup;$("#page-confirm").required=signup;$(".auth-page-submit").innerHTML=signup?'Create account <span>↗</span>':'Sign in <span>↗</span>';$("#page-switch").innerHTML=signup?'Already a member? <button type="button">Sign in</button>':'New to MAYOR VOGUE? <button type="button">Create an account</button>';$("#page-switch button").onclick=()=>pageAuthMode(!signup)}
function openAuthPage(signup=false){location.hash="login-page";pageAuthMode(signup)}
$("#auth-page-close").onclick=()=>location.hash="home";
$("#auth-page-form").onsubmit=async e=>{e.preventDefault();let signup=$("#auth-page-form").classList.contains("signup-mode"),email=$("#page-email").value.trim().toLowerCase(),password=$("#page-password").value;if(signup&&password!==$("#page-confirm").value){$("#page-message").textContent="Passwords do not match.";$("#page-message").style.color="#b45c48";return}try{let result=await api(signup?"/api/auth/register":"/api/auth/login",{method:"POST",body:JSON.stringify(signup?{name:$("#page-name").value.trim(),email,password}:{email,password})});accountUser=result.user;$("#page-message").textContent=result.message||"Signed in successfully.";$("#page-message").style.color="#4f805f"}catch(error){$("#page-message").textContent=error.message;$("#page-message").style.color="#b45c48"}};
$("#page-forgot").onclick=async()=>{let email=prompt("Enter the email address for your password reset link:");if(email){try{let result=await api("/api/auth/forgot-password",{method:"POST",body:JSON.stringify({email})});$("#page-message").textContent=result.message}catch(error){$("#page-message").textContent=error.message}}};
if(location.hash==="#login-page")pageAuthMode(false);
$("#currency").value=currency;renderProducts();renderCart();
$("#current-year").textContent=new Date().getFullYear();
async function syncAdminView(){
  const isAdminRoute=location.hash.startsWith("#admin");
  document.body.classList.toggle("admin-mode",isAdminRoute);
  document.body.classList.remove("admin-authorized");
  if(!isAdminRoute)return;
  try{
    const data=await api("/api/admin/overview");
    document.body.classList.add("admin-authorized");
    const metrics=data.metrics;
    $("#admin-total-revenue").textContent=money(metrics.totalRevenueMinor);
    $("#admin-total-orders").textContent=metrics.totalOrders;
    $("#admin-total-customers").textContent=metrics.totalCustomers;
    $("#admin-total-products").textContent=metrics.totalProducts;
    $("#admin-pending-orders").textContent=metrics.pendingOrders;
    $("#admin-completed-orders").textContent=metrics.completedOrders;
    $("#admin-low-stock").textContent=metrics.lowStockProducts;
    await loadAdminProducts();
    await loadAdminOrders();
    await loadAdminAnalytics();
  }catch(error){
    if(error.message==="Administrator access required"||error.message==="Authentication required"||error.message==="Session expired"){location.hash="home";return}
    console.error(error);
  }
}
let adminProducts=[];
    const productFieldIds=["product-name","product-slug","product-sku","product-category","product-gender","product-price","product-discount","product-cost","product-stock","product-low-stock","product-sizes","product-colours","product-images","product-variants","product-seo-title","product-seo-description","product-short-description","product-description"];
    const escapeHtml=value=>String(value??"").replace(/[&<>"']/g,character=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[character]));
    async function loadAdminProducts(){const result=await api("/api/admin/products");adminProducts=result.products;$("#admin-products-list").innerHTML=adminProducts.map(product=>`<div class="admin-product-row"><div><strong>${escapeHtml(product.name)}</strong><small>${escapeHtml(product.sku)} · ${escapeHtml(product.category)} · ${product.stockQuantity} in stock</small></div><span class="${product.active?"product-active":"product-inactive"}">${product.active?"Active":"Inactive"}</span><div class="product-actions"><button data-product-edit="${product.id}">Edit</button><button data-product-duplicate="${product.id}">Duplicate</button><button data-product-toggle="${product.id}">${product.active?"Deactivate":"Activate"}</button><button data-product-delete="${product.id}">Delete</button></div></div>`).join("")||"<p>No products found.</p>"}
    let adminOrders=[],selectedOrder=null;
    const orderStatusNames={PENDING:"Pending",PAID:"Paid",PROCESSING:"Processing",PACKED:"Packed",SHIPPED:"Shipped",OUT_FOR_DELIVERY:"Out for Delivery",DELIVERED:"Delivered",CANCELLED:"Cancelled",RETURNED:"Returned",REFUNDED:"Refunded"};
    async function loadAdminOrders(){let query=new URLSearchParams();if($("#admin-order-search").value.trim())query.set("search",$("#admin-order-search").value.trim());if($("#admin-order-status").value)query.set("status",$("#admin-order-status").value);let result=await api(`/api/admin/orders?${query}`);adminOrders=result.orders;$("#admin-orders-list").innerHTML=adminOrders.map(order=>`<button class="admin-order-row" data-order-id="${order.id}"><strong>${escapeHtml(order.orderNumber)}</strong><span>${escapeHtml(order.email)}</span><span>${new Date(order.createdAt).toLocaleDateString()}</span><b>${escapeHtml(order.currency)} ${order.totalMinor.toLocaleString()}</b><em class="status">${orderStatusNames[order.status]||order.status}</em></button>`).join("")||"<p>No orders found.</p>"}
    function renderAnalyticsList(selector,items,labelKey,valueKey){$(selector).innerHTML=items.length?items.map(item=>`<div><span>${escapeHtml(item[labelKey])}</span><b>${item[valueKey].toLocaleString()}</b></div>`).join(""):"<p>No data yet.</p>"}
    async function loadAdminAnalytics(){const result=await api("/api/admin/analytics"),summary=result.summary;const format=value=>money(value);$("#analytics-daily-sales").textContent=format(summary.dailySalesMinor);$("#analytics-weekly-sales").textContent=format(summary.weeklySalesMinor);$("#analytics-monthly-sales").textContent=format(summary.monthlySalesMinor);$("#analytics-aov").textContent=format(summary.averageOrderValueMinor);$("#analytics-new-customers").textContent=summary.newCustomers;$("#analytics-returning-customers").textContent=summary.returningCustomers;$("#analytics-conversion").textContent=summary.conversionRate===null?"Unavailable":`${summary.conversionRate}%`;$("#analytics-abandoned-carts").textContent=summary.abandonedCarts===null?"Unavailable":summary.abandonedCarts;const max=Math.max(...result.dailySales.map(item=>item.revenueMinor),1);$("#analytics-revenue-chart").innerHTML=result.dailySales.map(item=>`<span title="${item.date}: ${format(item.revenueMinor)}" style="height:${Math.max(4,item.revenueMinor/max*100)}%"></span>`).join("");renderAnalyticsList("#analytics-best-products",result.bestSellingProducts,"name","quantity");renderAnalyticsList("#analytics-best-categories",result.bestSellingCategories,"category","quantity");renderAnalyticsList("#analytics-viewed-products",result.mostViewedProducts,"name","views")}
    function renderOrderDetails(order){selectedOrder=order;$("#admin-order-details").hidden=false;$("#admin-order-details").innerHTML=`<div class="admin-card-head"><div><p class="eyebrow">ORDER DETAILS</p><h2>${escapeHtml(order.orderNumber)}</h2><p>${escapeHtml(order.user?.name||order.email)} · <a href="mailto:${escapeHtml(order.email)}">Contact customer</a></p></div><button type="button" data-order-close>×</button></div><div class="order-detail-items">${order.items.map(item=>`<div><span>${escapeHtml(item.productName)} × ${item.quantity}</span><b>${order.currency} ${(item.unitPriceMinor*item.quantity).toLocaleString()}</b></div>`).join("")}</div><div class="order-update-grid"><label>Status<select id="order-detail-status">${Object.entries(orderStatusNames).map(([value,label])=>`<option value="${value}" ${order.status===value?"selected":""}>${label}</option>`).join("")}</select></label><label>Carrier<input id="order-carrier" value="${escapeHtml(order.carrier||"")}"></label><label>Tracking details<input id="order-tracking" value="${escapeHtml(order.trackingNumber||"")}"></label></div><div class="product-actions"><button type="button" data-order-save>Save delivery update</button><button type="button" data-order-refund>Process refund</button><button type="button" data-order-cancel>Cancel order</button></div>`}
    $("#admin-order-search").oninput=()=>loadAdminOrders().catch(error=>$("#admin-order-message").textContent=error.message);$("#admin-order-status").onchange=()=>loadAdminOrders().catch(error=>$("#admin-order-message").textContent=error.message);$("#admin-orders-list").onclick=async event=>{let row=event.target.closest("[data-order-id]");if(!row)return;try{let result=await api(`/api/admin/orders/${row.dataset.orderId}`);renderOrderDetails(result.order)}catch(error){$("#admin-order-message").textContent=error.message}};
    $("#admin-order-details").onclick=async event=>{let button=event.target.closest("button");if(!button)return;if(button.dataset.orderClose){$("#admin-order-details").hidden=true;return}try{if(button.dataset.orderSave){let result=await api(`/api/admin/orders/${selectedOrder.id}/status`,{method:"PATCH",body:JSON.stringify({status:$("#order-detail-status").value,carrier:$("#order-carrier").value,trackingNumber:$("#order-tracking").value})});renderOrderDetails(result.order);await loadAdminOrders()}else if(button.dataset.orderRefund){if(confirm("Process this refund?")){await api(`/api/admin/orders/${selectedOrder.id}/refund`,{method:"POST"});$("#admin-order-message").textContent="Refund processed.";await loadAdminOrders()}}else if(button.dataset.orderCancel){await api(`/api/admin/orders/${selectedOrder.id}/status`,{method:"PATCH",body:JSON.stringify({status:"CANCELLED",carrier:selectedOrder.carrier,trackingNumber:selectedOrder.trackingNumber})});$("#admin-order-message").textContent="Order cancelled.";await loadAdminOrders()}}catch(error){$("#admin-order-message").textContent=error.message}};
    $("#print-order").onclick=()=>{if(!selectedOrder){$("#admin-order-message").textContent="Select an order first.";return}const invoice=window.open("","_blank","width=800,height=900");invoice.document.write(`<html><head><title>Invoice ${escapeHtml(selectedOrder.orderNumber)}</title></head><body><h1>MAYOR VOGUE</h1><h2>Invoice ${escapeHtml(selectedOrder.orderNumber)}</h2><p>${escapeHtml(selectedOrder.email)}</p>${selectedOrder.items.map(item=>`<p>${escapeHtml(item.productName)} × ${item.quantity} — ${selectedOrder.currency} ${(item.unitPriceMinor*item.quantity).toLocaleString()}</p>`).join("")}<h3>Total: ${selectedOrder.currency} ${selectedOrder.totalMinor.toLocaleString()}</h3><script>window.print()</script></body></html>`);invoice.document.close()};
    function resetProductForm(){document.querySelector("#admin-product-form").reset();$("#product-id").value="";$("#product-low-stock").value=5;$("#product-variants").value="{}";$("#product-form-title").textContent="Add product"}
    function fillProductForm(product){$("#product-id").value=product.id;$("#product-form-title").textContent="Edit product";$("#product-name").value=product.name;$("#product-slug").value=product.slug;$("#product-sku").value=product.sku;$("#product-category").value=product.category;$("#product-gender").value=product.gender||"";$("#product-price").value=product.priceMinor;$("#product-discount").value=product.discountMinor??"";$("#product-cost").value=product.costMinor??"";$("#product-stock").value=product.stockQuantity;$("#product-low-stock").value=product.lowStockAt;$("#product-sizes").value=product.sizes.join(", ");$("#product-colours").value=product.colours.join(", ");$("#product-images").value=product.images.map(image=>image.url).join("\n");$("#product-variants").value=JSON.stringify(product.variants||{},null,2);$("#product-seo-title").value=product.seoTitle||"";$("#product-seo-description").value=product.seoDescription||"";$("#product-short-description").value=product.shortDescription||"";$("#product-description").value=product.description;$("#product-active").checked=product.active;$("#product-featured").checked=product.featured;$("#product-best-seller").checked=product.bestSeller;$("#product-new-arrival").checked=product.newArrival}
    async function uploadProductImages(){const files=[...$("#product-image-files").files];return Promise.all(files.map(file=>new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=async()=>{try{const result=await api("/api/admin/uploads",{method:"POST",body:JSON.stringify({filename:file.name,contentType:file.type,data:reader.result})});resolve(result.url)}catch(error){reject(error)}};reader.onerror=()=>reject(new Error(`Could not read ${file.name}`));reader.readAsDataURL(file)})))}
    async function productPayload(){let optionalNumber=id=>$(id).value===""?null:Number($(id).value);let variants;try{variants=JSON.parse($("#product-variants").value||"{}")}catch{throw new Error("Variants must be valid JSON")}const uploaded=await uploadProductImages();const urls=$("#product-images").value.split(/\r?\n/).map(url=>url.trim()).filter(Boolean).concat(uploaded);return {name:$("#product-name").value.trim(),slug:$("#product-slug").value.trim(),sku:$("#product-sku").value.trim(),category:$("#product-category").value.trim(),gender:$("#product-gender").value.trim()||null,priceMinor:Number($("#product-price").value),discountMinor:optionalNumber("#product-discount"),costMinor:optionalNumber("#product-cost"),stockQuantity:Number($("#product-stock").value),lowStockAt:Number($("#product-low-stock").value),sizes:$("#product-sizes").value.split(",").map(value=>value.trim()).filter(Boolean),colours:$("#product-colours").value.split(",").map(value=>value.trim()).filter(Boolean),images:urls.map(url=>({url:url.startsWith("/")?location.origin+url:url,alt:$("#product-name").value.trim()})),variants,seoTitle:$("#product-seo-title").value.trim()||null,seoDescription:$("#product-seo-description").value.trim()||null,shortDescription:$("#product-short-description").value.trim()||null,description:$("#product-description").value.trim(),active:$("#product-active").checked,featured:$("#product-featured").checked,bestSeller:$("#product-best-seller").checked,newArrival:$("#product-new-arrival").checked}}
    $("#new-product").onclick=()=>{$("#admin-product-form").hidden=false;resetProductForm();$("#admin-product-form").scrollIntoView({behavior:"smooth"})};$("#cancel-product").onclick=()=>$("#admin-product-form").hidden=true;
    $("#admin-product-form").onsubmit=async event=>{event.preventDefault();try{let id=$("#product-id").value,payload=await productPayload();await api(id?`/api/admin/products/${id}`:"/api/admin/products",{method:id?"PATCH":"POST",body:JSON.stringify(payload)});$("#admin-product-message").textContent="Product saved.";$("#admin-product-form").hidden=true;await loadAdminProducts()}catch(error){$("#admin-product-message").textContent=error.message}};
    $("#admin-products-list").onclick=async event=>{let button=event.target.closest("button");if(!button)return;let id=button.dataset.productEdit||button.dataset.productDuplicate||button.dataset.productToggle||button.dataset.productDelete,product=adminProducts.find(item=>item.id===id);try{if(button.dataset.productEdit){$("#admin-product-form").hidden=false;fillProductForm(product);$("#admin-product-form").scrollIntoView({behavior:"smooth"})}else if(button.dataset.productDuplicate){await api(`/api/admin/products/${id}/duplicate`,{method:"POST"});await loadAdminProducts()}else if(button.dataset.productToggle){await api(`/api/admin/products/${id}/status`,{method:"PATCH",body:JSON.stringify({active:!product.active})});await loadAdminProducts()}else if(button.dataset.productDelete){if(confirm(`Delete ${product.name}?`)){await api(`/api/admin/products/${id}`,{method:"DELETE"});await loadAdminProducts()}}}catch(error){$("#admin-product-message").textContent=error.message}};
window.addEventListener("hashchange",syncAdminView);syncAdminView();
$("#admin-close").onclick=()=>location.hash="home";
document.querySelector('a[aria-label="Shopping cart"]').onclick=e=>{e.preventDefault();$("#cart-panel").classList.add("open");$("#modal-backdrop").classList.add("open")};
document.addEventListener("click",e=>{let addButton=e.target.closest("[data-add]"),wish=e.target.closest("[data-wish]"),view=e.target.closest("[data-view]"),remove=e.target.closest("[data-remove]"),qty=e.target.closest("[data-qty]");if(addButton){add(+addButton.dataset.add);$("#cart-panel").classList.add("open");$("#modal-backdrop").classList.add("open")}if(wish){let id=+wish.dataset.wish;wishlist.includes(id)?wishlist=wishlist.filter(x=>x!==id):wishlist.push(id);save();renderProducts();renderCart()}if(view&&!e.target.closest("button"))showQuick(+view.dataset.view);if(remove){cart=cart.filter(x=>x.id!==+remove.dataset.remove);save();renderCart()}if(qty){let item=cart.find(x=>x.id===+qty.dataset.qty);item.qty+=+qty.dataset.delta;if(item.qty<1)cart=cart.filter(x=>x.id!==item.id);save();renderCart()}});
$$(".filter-pill").forEach(b=>b.onclick=()=>{$$(".filter-pill").forEach(x=>x.classList.remove("active"));b.classList.add("active");activeFilter=b.dataset.filter;renderProducts()});$("#sort-products").onchange=renderProducts;$("#currency").onchange=e=>{currency=e.target.value;save();renderProducts();renderCart()};
$("#search-toggle").onclick=()=>$("#search-bar").classList.toggle("open");$("#search-input").oninput=e=>{let term=e.target.value.toLowerCase(),found=products.filter(p=>(p.name+p.type).toLowerCase().includes(term)).slice(0,4);$("#suggestions").innerHTML=term?found.map(p=>`<a class="suggestion" href="#shop"><img src="${p.image}" alt=""><span>${p.name}<br><small>${money(p.price)}</small></span></a>`).join(""):`<p style="padding:10px;color:var(--muted)">Try “loafer”, “watch” or “sneaker”.</p>`};
function closeOverlays(){$("#cart-panel").classList.remove("open");$("#quick-view").classList.remove("open");$("#modal-backdrop").classList.remove("open")}
$("#cart-close").onclick=closeOverlays;$("#quick-close").onclick=closeOverlays;$("#modal-backdrop").onclick=closeOverlays;$(".menu-toggle").onclick=()=>{$("#mobile-drawer").classList.add("open");$("#drawer-backdrop").classList.add("open")};$(".drawer-close").onclick=()=>{$("#mobile-drawer").classList.remove("open");$("#drawer-backdrop").classList.remove("open")};$("#drawer-backdrop").onclick=()=>{$("#mobile-drawer").classList.remove("open");$("#drawer-backdrop").classList.remove("open")};$$(".mobile-drawer a").forEach(a=>a.onclick=()=>$("#drawer-backdrop").click());
$("#newsletter-form").onsubmit=e=>{e.preventDefault();$("#newsletter-message").textContent="Thank you — you’re on the list.";e.target.reset()};
$("#checkout-button").onclick=async()=>{if(!cart.length){$("#payment-message").textContent="Add an item before checkout.";return}let email=accountUser?.email||prompt("Enter your email for payment:");if(!email)return;let provider=$("#payment-provider").value;$("#checkout-button").disabled=true;$("#payment-message").textContent="Securely connecting to "+(provider==="paystack"?"Paystack":"Flutterwave")+"…";try{let result=await api("/api/payments/initialize",{method:"POST",body:JSON.stringify({provider,email,currency:currency==="BTC"?"NGN":currency,items:cart.map(item=>({sku:products.find(p=>p.id===item.id).sku,quantity:item.qty}))})});$("#payment-message").textContent="Redirecting to secure payment…";location.href=result.authorizationUrl}catch(error){$("#payment-message").textContent=error.message;$("#payment-message").style.color="#b45c48";$("#checkout-button").disabled=false}};
if(!document.querySelector("#auth-form")){const legacyAuthForm=document.createElement("form");legacyAuthForm.id="auth-form";legacyAuthForm.hidden=true;document.body.appendChild(legacyAuthForm)}
$("#auth-form").onsubmit=async e=>{e.preventDefault();let email=$("#auth-email").value.trim().toLowerCase(),password=$("#auth-password").value,confirm=$("#auth-confirm").value;if($("#account-modal").classList.contains("signup-mode")&&password!==confirm){setAuthMessage("Passwords do not match.",true);return}try{let path=$("#account-modal").classList.contains("signup-mode")?"/api/auth/register":"/api/auth/login";let payload=$("#account-modal").classList.contains("signup-mode")?{name:email.split("@")[0],email,password}:{email,password};let result=await api(path,{method:"POST",body:JSON.stringify(payload)});accountUser=result.user;showDashboard()}catch(error){setAuthMessage(error.message,true)}};
const originalShowQuick=showQuick;showQuick=id=>{recent=[id,...recent.filter(x=>x!==id)].slice(0,4);localStorage.setItem("mv-recent",JSON.stringify(recent));originalShowQuick(id)};
async function loadCustomerAccount(){
  if(!accountUser)return;
  try{
    const me=await api("/api/auth/me"); accountUser=me.user;
    $("#account-name").value=accountUser.name||"";$("#account-email").value=accountUser.email;$("#account-phone").value=accountUser.phone||"";
    const orders=await api("/api/account/orders");$("#account-orders-list").innerHTML=orders.orders.map(order=>`<div><span><strong>${order.orderNumber}</strong><small>${order.status} · ${order.items.length} item(s)</small></span><b>${order.currency} ${order.totalMinor.toLocaleString()}</b></div>`).join("")||"<p>No orders yet.</p>";
    renderAccountProducts("#account-wishlist-list",wishlist,"Your wishlist is empty.");renderAccountProducts("#account-recent-list",recent,"No recently viewed products.");
    const addresses=await api("/api/account/addresses");$("#address-list").innerHTML=addresses.addresses.map(address=>`<div><span><strong>${address.label}${address.isDefault?" · Default":""}</strong><small>${address.street}, ${address.city}, ${address.state}</small></span><button type="button" data-default-address="${address.id}">Set default</button></div>`).join("")||"<p>No saved addresses.</p>";
  }catch(error){console.error(error)}
}
function renderAccountProducts(selector,ids,empty){const items=ids.map(id=>products.find(product=>product.id===id)).filter(Boolean);$(selector).innerHTML=items.map(product=>`<div><span><strong>${escapeHtml(product.name)}</strong><small>${money(product.price)}</small></span><button type="button" data-add="${product.id}">Reorder</button></div>`).join("")||`<p>${empty}</p>`}
$("#account-profile-form").onsubmit=async event=>{event.preventDefault();try{const result=await api("/api/account/profile",{method:"PATCH",body:JSON.stringify({name:$("#account-name").value.trim(),phone:$("#account-phone").value.trim()})});accountUser=result.user;alert("Profile saved.")}catch(error){alert(error.message)}};
$("#account-password-form").onsubmit=async event=>{event.preventDefault();try{await api("/api/account/password",{method:"PATCH",body:JSON.stringify({currentPassword:$("#account-current-password").value,newPassword:$("#account-new-password").value})});event.target.reset();alert("Password changed successfully.")}catch(error){alert(error.message)}};
$("#address-form").onsubmit=async event=>{event.preventDefault();try{await api("/api/account/addresses",{method:"POST",body:JSON.stringify({label:$("#address-label").value,street:$("#address-street").value,city:$("#address-city").value,state:$("#address-state").value})});event.target.reset();await loadCustomerAccount()}catch(error){alert(error.message)}};
$("#address-list").onclick=async event=>{const button=event.target.closest("[data-default-address]");if(!button)return;try{await api(`/api/account/addresses/${button.dataset.defaultAddress}/default`,{method:"PATCH"});await loadCustomerAccount()}catch(error){alert(error.message)}};
window.addEventListener("hashchange",()=>{if(location.hash.startsWith("#account-"))loadCustomerAccount()});
initializeSiteAuth();
